---
language: python
sudo: true
addons:
  apt:
    packages:
    - texlive-base
    - texlive-latex-recommended
    - texlive-extra-utils
    - texlive-fonts-recommended
    - texlive-font-utils
    - texlive-lang-french
    - texlive-latex-extra
    - texlive-math-extra
    - texlive-xetex
    - texlive-pictures
    - pgf
    - latex-xcolor
    - lmodern
    - latexmk
os:
  - linux
python:
  - 2.7
before_install:
  - sudo apt-get update -qq 
  - sudo apt-get install graphviz
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20160619/texlive.tar.xz | tar -JxC $HOME/texlive
install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - pip install dot2tex
  - pip install graphviz
  - tlmgr update --self --all
  - tlmgr install babel-french
script:
  - make a4
  - make c5
