sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq texlive-xetex texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra

before_script:
  - sudo tlmgr update --self
  - sudo tlmgr update --all

install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - sudo pip install pygments
  - sudo pip install pygments-style-solarized
  - sudo pip install dot2tex
  - sudo pip install graphviz

script:
  - make a4
  - make c5
